version: "3"
services:
  db:
    container_name: db
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
